### ISSUE TITLE
Error when run the example

### ISSUE THREAD

**Issue by cmbreki** [B-3PO/angular-material-expansion-panel#31]
Hello, 
I get the following error when i try the page example:
"ExpansionPanel 'panelOne' is not available! Did you use md-component-id='panelOne'?"
Any ideas?

**Comment by B-3PO** [comment]
what branch did you pull?

**Comment by cmbreki** [comment]
I used bower install. Should i pull the master branch?

**Comment by B-3PO** [comment]
Thats why, you need to pull a branch and run gulp. You can pull master or any of the release branches.

**Comment by chetanku** [comment]
I am still not able to get it work. I took the master branch followed by:
npm install
gulp build
The build goes fine.
I see the js and css getting updated in the dist folder.
gulp test passes
and I get the error:

angular.js:14328 ExpansionPanel 'panelOne' is not available! Did you use md-component-id='panelOne'?
angular.js:14328 TypeError: Cannot read property 'expand' of undefined ..

Code samples works fine.

I tried bower install as well instead of pulling the master branch but that too fails with the same error.
any help will be great.

**Comment by B-3PO** [comment]
I need a little more info.
1. What version of angular?
2. What browser(s)?
3. Is this the test app that i wrote, or are you using your own code?
3.5. If this is your own code, can you post it.

**Comment by chetanku** [comment]
1. I am using angular version # 1.6.1
2. Chrome
3. The test app you wrote works fine. 
 My code 
 I have attached my code below, It is a sample app I am writing to explore angular-material-expansion-pane.

[index.html.txt](https://github.com/B-3PO/angular-material-expansion-panel/files/753196/index.html.txt)
[app.js.txt](https://github.com/B-3PO/angular-material-expansion-panel/files/753197/app.js.txt)

Appreciate your help.

**Comment by B-3PO** [comment]
If you look at the code, there are 2 styles (async, sync). The Sync style is causing your error. Remove that line of code(`$mdExpansionPanel('panelOne').expand();`) and just use the async style.

The problem is that angular has not yet rendered the panel at the time you are calling for it. That is why we have the waitfor method.

**Comment by chetanku** [comment]
Thanks Ben.
